#!/bin/csh -f
#	(C) Gleb Vdovin 1993-1996
#	This file is a part of LightPipes distribution
#	


#defocus
begin 0.025 5e-7 | circ_ap 0.01 | zernike 2 0 0.01 20 | b_split foo1 > foo
# Radial magnification
interpol same same 0. 0. 0 1.3 < foo1 | b_mix foo > foo2
# postscript output
file_ps radial1.ps  same < foo2 > /dev/null
# This will work if you have ghostview installed, otherwise comment it
show foo2
rm foo foo1 foo2

#spherical aberration
begin 0.025 5e-7 | circ_ap 0.01 | zernike 4 0 0.01 20 | b_split foo1 > foo
# Radial magnification
interpol same same 0. 0. 0 1.3 < foo1 | b_mix foo > foo2
# postscript output
file_ps radial2.ps same < foo2 > /dev/null
# This will work if you have ghostview installed, otherwise comment it
show foo2
rm foo foo1 foo2

#High order  aberration without axial symmetry
begin 0.025 5e-7 | circ_ap 0.01 |zernike 10 4 0.01 20 | b_split foo1 > foo
# Radial magnification
interpol same same 0. 0. 0 1.3 < foo1 | b_mix foo > foo2
# postscript output
file_ps radial3.ps same < foo2 > /dev/null
# This will work if you have ghostview installed, otherwise comment it
show foo2
rm foo foo1 foo2
