#!/bin/csh -f
#	(C) Gleb Vdovin 1993-1996
#	This file is a part of LightPipes  distribution
#	

begin 0.015 5e-7 | circ_ap 0.005 | fresnel 0.5 | b_split foo 0.3 > foo1
# Propagation to mirror1, reflection,
# propagation back and beamsplitter again
fresnel 1 < foo | absorber  0.7 > foo2
# Propagation to mirror2, reflection,
# propagation back and beamsplitter again
fresnel 0.4 < foo1 | zernike 3 1 0.005 25 | fresnel 0.4 | absorber  0.3 > foo3
# mixing the two beams and propagation to the screen
b_mix foo2 < foo3 | fresnel 1 | file_ps tg.ps same > foo1
echo "Interferomgram simulated:"
show foo1
# deleting the temp files
rm foo foo1 foo2 foo3
